### ISSUE TITLE
Changing the scrollable area

### ISSUE THREAD

**Issue by grahammcuk** [julianlloyd/scrollReveal.js#118]
I have a page that has a fixed div within it which is 100% the width/height of the viewport. Obviously the animations aren't being applied to the divs within this, as the plugin is only monitoring the scroll of the page as a whole.

I have configured the plugin to look for the scrolling of the inner div by adding `viewport: document.getElementById("main"),` to the script, but this doesn't seem to have fixed the issue. 

How do a change the 'scrollable' area that ScrollReveal monitors?

Thanks

**Comment by julianlloyd** [comment]
Hey @grahammcuk,

Truthfully, custom viewports are the least tested area of ScrollReveal. Any chance you could recreate your markup with http://jsbin.com?

**Comment by grahammcuk** [comment]
Hi, 

Apologies for the delay. I have quickly thrown together a codepen to demonstrate my issue:

http://codepen.io/grahammcuk/pen/ogBNdp

Any help would be greatly appreciated.

Thanks

**Comment by grahammcuk** [comment]
I have also put this question out to the StackOverflow community:

http://stackoverflow.com/questions/27820482/changing-scrollreveal-js-viewport

Hopefully there will be a way of doing it

**Comment by grahammcuk** [comment]
Hi @julianlloyd ,

I don't suppose you've had chance to take a look at this yet:)

Thanks

**Comment by julianlloyd** [comment]
Not yet @grahammcuk.

**Comment by iamgena** [comment]
Maybe silly, but do you have it as 
viewport: document.getElementById("main")
or viewport: document.getElementById(".main") < assuming main is class?

**Comment by julianlloyd** [comment]
Check it out @grahammcuk 

http://codepen.io/anon/pen/ByRxKG

- Your element `<main id="mainn">` had a typo, so I changed the `id` to `main`
- The scrollReveal constructor wasn’t being customized with a viewport, so I added one.

Does this help?

**Comment by julianlloyd** [comment]
Check it out @grahammcuk 

http://codepen.io/anon/pen/ByRxKG

- Your element `<main id="mainn">` had a typo, so I changed it to `<main id='main'>`
- The scrollReveal constructor wasn’t being customized with a viewport, so I added one:

```javascript
window.sr = new scrollReveal({
  viewport: document.getElementById('main')
});
```

**Comment by grahammcuk** [comment]
Doh! Knew it had to something stupid! Thanks very much for your help :+1:
