### ISSUE TITLE
implement paralax 

### ISSUE THREAD

**Issue by jurgob** [julianlloyd/scrollReveal.js#121]
it is possible to implement paralax effect with scrollReveal?

if so, can I have a working example?

**Comment by julianlloyd** [comment]
Hey @jurgob,

ScrollReveal more or less does 2 things:
- Checks when elements are "visible"
- Adds/removes styles for appropriate animations

There’s no reason you couldn’t use it in conjunction with your parallax effect, but the library itself does not handle anything related to parallax directly.
