### ISSUE TITLE
Multiple entry direction possible?

### ISSUE THREAD

**Issue by benhanks040888** [julianlloyd/scrollReveal.js#123]
Hi, is it possible to add support for multiple entry direction?
e.g. `enter top left` or `enter bottom right`?

**Comment by ivansglazunov** [comment]
At different times, under different conditions?
For example `toggle`? I think the simple conditions like this can be done. But the condition on js require a reinitialization or a handler in JavaScript. I think if we make JS API, it is possible.
For now:

**Comment by benhanks040888** [comment]
Not exactly, I just want the element to animate in from top left instead of from top or left only.

**Comment by ivansglazunov** [comment]
Got It. It would be cool.

**Comment by julianlloyd** [comment]
@ivansglazunov @benhanks040888 

So, something like:
```html
<div data-sr="enter top left over 1s"> Foo </div>
<div data-sr="enter top right over 2s"> Foo </div>
<div data-sr="enter bottom left over 3s"> Foo </div>
<div data-sr="enter bottom right over 4s"> Foo </div>
```
??

**Comment by benhanks040888** [comment]
Yes. Perhaps `top-left` instead of `top left` to make it more explicit?

Would be cool. Thanks!
