### ISSUE TITLE
how to scrollreveal elements in a bootstrap modal?

### ISSUE THREAD

**Issue by Unit60** [julianlloyd/scrollReveal.js#124]
I'm an absolute javascript novice (but learning)... I love this plugin, but I can't figure out why the elements are not being triggered when they sit in a bootstrap modal?

The position of the div is fixed and initially `display: none` and I’ve tried:
```JavaScript
viewport: document.getElementsById( 'modal' )
viewport: document.getElementsByClassName( 'modal' )
```

but no cigar :disappointed:  
Any help would be appreciated!

**Comment by AlchemyUnited** [comment]
I'm not sure, but I'm gonna take a wild guess...The modal - and all within it - is, in a way, already within the viewport. Sure you're scrolling with the modal, but from the perspective of scrollreveal all that stuff is - via the modal - already revealed. 

Again, just a guess.

**Comment by Unit60** [comment]
ScrollReveal is adding the class transforms to the element I want to animate in the modal (cool so far), but they just don't fire (fade or animate in)... I can see them in the dev-inspector, sitting in the modal ready to fire, but they just don't activate... unless I resize the viewport, then they fire... so it has something to do with the viewport?!

**Comment by Unit60** [comment]
AHA... I got it working in the modal (parent position:fixed) with:
window.sr = new scrollReveal({
viewport: document.getElementById('defaultModal')
});
Same issue as:
https://github.com/julianlloyd/scrollReveal.js/issues/118

But now I have the problem that scrollReveal only works for the modal and not the main page... I can't select multiple id's (as this is how modal's are called)... so I need to getElementBy... some thing else?!
I'm such a novice with javaScript... a steer in the right direction would be appreciated!

**Comment by Unit60** [comment]
OK... I've made a rudimentary mock-up of what I am trying to do in this fiddle: http://jsfiddle.net/L0mx7f50/1/

I'm no coder (trying to learn) and am now up against a brick wall... please help :)

**Comment by julianlloyd** [comment]
So essentially, you need 2 instances of scrollReveal — one with the default viewport, and one with the modal as the viewport?

**Comment by Unit60** [comment]
I think I have bitten off way more than I can chew... tried to adapt the script with your suggestion in mind, but I doubt I have enough basic knowledge to get this to work... here is as far as I have got:
http://jsfiddle.net/L0mx7f50/3/

Beyond that, if there is more than 1 modal in a page I would have to create a new instance for each ID... is there perhaps a cleverer way?

**Comment by julianlloyd** [comment]
Perhaps use a single modal container, and swap out the content… rather than creating discreet modals, but like I mentioned before, I haven’t done much testing when working with multiple instances of scrollReveal.

If you’d like, open a separate issue requesting support for multiple scrollReveal instances. In the meantime, I’m closing and ice boxing this one.

**Comment by Unit60** [comment]
Thanks Julian... I'll open a request :)
