### ISSUE TITLE
Creating BounceIn Effect

### ISSUE THREAD

**Issue by WPThemer** [julianlloyd/scrollReveal.js#127]
I am sorry I dont know where to post this, but I wanted to create a BounceIn effect, so I did this and sharing if one needs it, for this you need to modify the original JS file and add another case: for bouncein..

Find the following line add code below this line....
switch ( keyword ) {

here is the code...
-----------------------------------
          case 'bouncein':

            if ( words[ i + 1 ] == 'up' || words[ i + 1 ] == 'down' ) {
              parsed.scale.direction = words[ i + 1 ]
              parsed.easing  = 'cubic-bezier(0.495, 0.055, 0.095, 1.475)'
              return
            }

            parsed.move   = words[ i + 1 ]
            parsed.easing = 'cubic-bezier(0.495, 0.055, 0.095, 1.475)'
            return

you can use it like this:
enter right bouncein 500px over .5s
enter left bouncein 500px over .5s
enter top bouncein 500px over .5s
enter bottom bouncein 500px over .5s

cheers

**Comment by julianlloyd** [comment]
Hey @WPThemer thanks for this.

I’ll work on getting this in the upcoming `v2.2` release. I need to re-think how easing keywords work for `v2.2`, but I’ll look into adding support for this.

:beers:

**Comment by WPThemer** [comment]
Great Julian !..

It will be great if in next versions we can specify "leave" and "fade" keyword with comma, for example if I want element to fadeIn when entering viewport and fadeout (controlling opacity with keyword fade) when leaving viewport, for example:

enter top fade 100px, leave bottom (or detect) fade 100px

I did not specify "fadeIN" the IN and OUT part, because if someone is scrolling down, when the element reached top, it should automatically detect the direction and fades out to top while fading (leaving port), and if someone scrolling up, it would fade out to down.. 

I believe I somehow tried to make it clear :) but it would be a good addition.

regards

**Comment by jlmakes** [comment]
**Update Jan 13th, 2016:**

Using ScrollReveal 3 you can easily use your own easing configuration.

_Example using ScrollReveal 3:_
```js
window.sr = ScrollReveal().reveal( '.fooClass', { easing : 'cubic-bezier(0.495, 0.055, 0.095, 1.475)' } );
```
