### ISSUE TITLE
Unreveal div with opacity

### ISSUE THREAD

**Issue by Artenis** [julianlloyd/scrollReveal.js#131]
Hi, is it possible to unreveal a div with opacity with ScrollReveal.js.
For example, on the head of website, the first div is visible, when i scroll down slowly the div loose opacity. Here is an example : http://ivang-design.com/apollo/slider/

**Comment by julianlloyd** [comment]
Hey @Artenis 

Maybe something like (Skrollr)[https://github.com/Prinzhorn/skrollr] [Scroll Magic](http://janpaepke.github.io/ScrollMagic/) would be better suited for this?

That effect binds opacity to scroll distance, whereas scrollReveal triggers animations based on element visibility; in other words, there is no way for scrollReveal to *partially* reveal an element, let alone partially un-reveal one.

**Comment by julianlloyd** [comment]
Hey @Artenis 

Maybe something like [Skrollr](https://github.com/Prinzhorn/skrollr) or [Scroll Magic](http://janpaepke.github.io/ScrollMagic/) would be better suited for this?

That effect binds opacity to scroll distance, whereas scrollReveal triggers animations based on element visibility; in other words, there is no way for scrollReveal to *partially* reveal an element, let alone partially un-reveal one.

Best of luck!
