### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by KyleAMathews** [julianlloyd/scrollReveal.js#133]
Looks like everything is already setup, you just need to type `npm publish`.

Browserify/Webpack users would be happy :)

**Comment by julianlloyd** [comment]
Thanks @KyleAMathews 

I setup an npm user account to attempt publishing, but encountered:
`Error: forbidden New packages must have all-lowercase names: scrollReveal.js`

I’ll get this squared away!

**Comment by KyleAMathews** [comment]
https://www.npmjs.com/package/scroll-reveal is open :)

**Comment by julianlloyd** [comment]
There is a new `scrollreveal` NPM package, published as of today’s `v2.2.0` ;)

Thanks again @KyleAMathews

**Comment by KyleAMathews** [comment]
Thanks!
