### ISSUE TITLE
Animation is performing in only one direction

### ISSUE THREAD

**Issue by pavankumarkatakam** [julianlloyd/scrollReveal.js#135]
Im using scroll reveal js and my configuration is  
```javascript
window.sr = new scrollReveal({
  reset: true,
  move: '50px',
  mobile: true,
  vFactor: 0.3
});
```

Now, when i scrolling from top to bottom the animations doesn’t occur… but when scrolling from bottom to top the animation is performing.

**Comment by julianlloyd** [comment]
Heyyooo @pavankumarkatakam 

Are you working with other 3rd parties? Wordpress? Other JavaScript libraries?

**Comment by pavankumarkatakam** [comment]
Im using Jquery,Bootstrap and Smoot scroll js. why closed?

**Comment by pavankumarkatakam** [comment]
i tested it by removing the SmoothScroll. but no result.

**Comment by pavankumarkatakam** [comment]
please take loot at this... Invizotechnologies.com

**Comment by julianlloyd** [comment]
What should I be looking at? It appears to be working…

**Comment by pavankumarkatakam** [comment]
When scrolling from top to bot to animation is performing before they appear in to viewport.... Check once clearly....

**Comment by umdieecke** [comment]
@pavankumarkatakam check out issue #111 . Set html, body { height: 100%; }
This worked for me.

**Comment by pavankumarkatakam** [comment]
Thanks for reply @umdieecke I will try that now...

**Comment by pavankumarkatakam** [comment]
Yes its working now....Thanks again @umdieecke .
