### ISSUE TITLE
z-index not working for opacity?

### ISSUE THREAD

**Issue by Mustapha-Os** [julianlloyd/scrollReveal.js#136]
Hello there,

I Can't give a z-index value with opacity giving to div's, Am still noobie with JS but i debugged with the js file when i remove thous line's it work's fine with z-index's

Line 420: initial += '; opacity: ' + elem.config.opacity + '; '
Line 421: target  += '; opacity: 1; ';

Need help i can't popup any drop menu's outside the div's !

### ScreenShot
![ScreenShot](http://cl.ly/image/3k0K0B2G122u/Screen%20Shot%202015-03-15%20at%205.27.16%20PM.jpg)

**Comment by julianlloyd** [comment]
Hey @Mustapha-Os read this! http://philipwalton.com/articles/what-no-one-told-you-about-z-index/

It looks like this isn’t a bug, but actually a part of the z-index specification. If you can put together a [JSBin](http://jsbin.com), I can help troubleshoot but there may not be much we can do.
