### ISSUE TITLE
How would I define the attributes for data-sr in HAML?

### ISSUE THREAD

**Issue by jthk** [julianlloyd/scrollReveal.js#137]
#about-us
  .jumbotron.about-us
    .section-parallax-image.about-us
      .container
        %hr
        %h1.section-title{:data-sr => "move 25px"}

is giving me errors, any help would be greatly appreciated!

**Comment by jlmakes** [comment]
[How to do data attributes with HAML](http://stackoverflow.com/questions/24353788/how-to-do-data-attributes-with-haml-and-rails)
