### ISSUE TITLE
Trying to add data-sr using jquery

### ISSUE THREAD

**Issue by idizajn** [julianlloyd/scrollReveal.js#139]
Hello,

I am trying to add data-sr on document using next code:
```JavaScript
$(function() {
   $(".className").attr('data-sr','');
});
```
It shows `data-sr` on frontend, but ScrollReveal doesn’t work on those items at all...

Is that some issue or there is logical explanation?

**Comment by julianlloyd** [comment]
Hey @idizajn

ScrollReveal searches through the DOM during instantiation…
```JavaScript
// This is where ScrollReveal searches for data-sr attributes…
window.sr = new scrollReveal();
```
If you add new `data-sr` attributes, you need to tell ScrollReveal that things have changed since you instantiated by calling `sr.init()` — so you would do something like:
```JavaScript
$(function() {
  $(".className").attr('data-sr','');
  sr.init();
});
```

**Comment by oxgesports** [comment]
I am trying to use it in Webflow but it gives me an error 
`Uncaught ReferenceError: scrollReveal is not defined`

Jquery, ScrollReveal loads one after another still facing this issue
