### ISSUE TITLE
transition effect are not working in iphone

### ISSUE THREAD

**Issue by bbvasanth** [julianlloyd/scrollReveal.js#140]
Hi Julian,

Transition effect are not working in iPhone 5 & 6. 
Any idea about the issue.

**Comment by julianlloyd** [comment]
Hi @bbvasanth 

Scrolling often pauses all painting on mobile devices, so in other words, scrolling pauses animations… making the UX of something like ScrollReveal suffer.

For this reason, the [default configuration](https://github.com/julianlloyd/scrollReveal.js/blob/master/scrollReveal.js#L66) has ScrollReveal disabled on mobile, so you will want to set `mobile: true` like so:
```javascript
var config = { mobile: true };
window.sr = new scrollReveal( config );
```
For more information on customizing ScrollReveal, please see the [Configuration Wiki](https://github.com/julianlloyd/scrollReveal.js/wiki/Configuration).
