### ISSUE TITLE
Syntactic sugar no longer works in v2.2.0

### ISSUE THREAD

**Issue by AmadeusW** [julianlloyd/scrollReveal.js#141]
I copied animation properties `data-sr="enter from right, move 50px, no reset"` verbatim from an earlier project to the new project which uses scrollReveal.js **v2.2.0**. The original project used scrollReveal.js **v2.0.2**

The enter animation no longer worked:

This happened because scrollReveal tried to set invalid CSS style `translateundefined` instead of `translatex`

I fixed it by changing the animation property to `data-sr="enter right, move 50px, no reset"`

Did you remove the option to use syntactic sugar, or is this a bug?

**Comment by julianlloyd** [comment]
Great catch @AmadeusW 

I actually did remove the sugar as of `v2.2.0`. I noticed no issues in my cursory testing, so I thought it safe to remove, but clearly I missed some conflicts—the `enter` keyword in particular seems most affected by the loss of `from` or `from the`.

The sugar was a fun touch when I first launched, but the ScrollReveal declarations have grown more complicated (easing, rotation, etc.)—so I’ve been working to streamline things, including the removal of sugar and the double delay keywords (`wait` vs `after`) to just `wait`.

What do you think? Bring the sugar back :+1: :-1: ?

**Comment by AmadeusW** [comment]
Sorry, I should have re-read the docs

It was a fun feature but I bet it complicates stuff. Slightly :-1: I didn't use sugar that much. I always wrote `enter from` and occasionally added an `and`. 

Optional `from` would be on my nice-to-have list, unless this confused people thinking that without `from` animation was reversed.
