### ISSUE TITLE
Creating vFactor for single element

### ISSUE THREAD

**Issue by idizajn** [julianlloyd/scrollReveal.js#142]
Hello,

Would something like this be possible data-sr="enter bottom, move 100px, wait 0.8s, vFactor 0.1" ?
So thing is when there are some big elements with big height they are not loaded very well, this above would solve problem?

Thanks

**Comment by Sammii** [comment]
+1 This would be great! All of my elements are different sizes and some are quite large. It would be great to be able to modify vFactor on a case-by-case basis. Alternatively, maybe a "maximum" would be useful ... so it could be 60% but maximum of 100px.

**Comment by julianlloyd** [comment]
Hey @idizajn @Sammii 

This is honestly a great idea, and one that has been requested before (#94), I just got a little stuck on the syntax. Check out #94, throw in any of your own ideas, and let’s get this into the next release.

:beers:

**Comment by idizajn** [comment]
Hi, I am not very great frontend developer but why it is not possible that syntax is:
<div data-sr='enter top, vFactor 0.60'>Foo</div>

Same syntax for vFactor as in global configuration, just parse it to single element?

Once again sorry if in advanced frontend dev mind this above sounds stupid.

**Comment by Sammii** [comment]
@julianlloyd I agree with @idizajn that a syntax that would be consistent would be maybe `data-sr='enter top, vFactor 0.60'` or `data-sr='enter top, vF 0.60'`

I didn't realize that 'opacity' wasn't already functional inline; that would be great as well!

**Comment by julianlloyd** [comment]
Done. `v2.3.0` pushed, with support for `opacity` and `vFactor` keywords.

Thanks @Sammii and @idizajn !
