### ISSUE TITLE
Hi Julian

### ISSUE THREAD

**Issue by SergioMerida** [julianlloyd/scrollReveal.js#144]
I have a question, Im working in some page but when I scroll down or up it's not like smooth scroll, is there something that can fix that? thank you Julian and congrats scrollReveal Is Awesome.

**Comment by julianlloyd** [comment]
Hey @SergioMerida, thanks for the kind words.

I don’t actually know of any smooth scrolling libraries, as I generally prefer to let the browser handle it natively. You can use FireFox or install [this](https://chrome.google.com/webstore/detail/smoothscroll/nbokbjkabcmbfdlbddjidfmibcpneigj/related?hl=en) Chrome Extension for yourself, but I can’t personally recommend any JavaScript libraries.

:bee:
