### ISSUE TITLE
Set Different Opacities for mobile and desktop

### ISSUE THREAD

**Issue by evliu** [julianlloyd/scrollReveal.js#147]
Hi, I was wondering if it's possible to set two different opacities. Thanks!

**Comment by julianlloyd** [comment]
Hey @evliu 

The current API does not differentiate between mobile and desktop animations. The only effect you can target directly on mobile is delay, by [editing the source](https://github.com/julianlloyd/scrollReveal.js/blob/master/scrollReveal.js#L373):
```javascript
  // Want to disable delay on mobile devices? Uncomment the line below.
  // if ( self.isMobile() && self.config.mobile ) cfg.wait = 0;
```
I’m not sure how useful this is, but considering that CSS animations pause while dragging your finger, I left this one-liner in there for anyone looking to salvage their animation UX.

I suppose you could roll your own solution by modifying the above code, to something like…
```javascript
  if ( self.isMobile() && self.config.mobile ) cfg.opacity = 0.5;
```
This would change the starting opacity on mobile devices to `0.5`, regardless of the styles generated from your config. (I wonder if I should add this to the feature request icebox…)

:bee:

**Comment by julianlloyd** [comment]
I’m going to icebox this as a feature request for future versions of ScrollReveal.

Thanks @evliu :beers:

**Comment by evliu** [comment]
Thanks, I'll be using that solution! I appreciate your quick response!

**Comment by addedlovely** [comment]
That one liner has just saved the day! +1

**Comment by jlmakes** [comment]
**Update Jan 13, 2016:**

For anyone stumbling upon this, ScrollReveal 3 can accomplish this with far more complexity. You can use the `tools.isMobile()` method to check for mobile and set completely unique configurations for mobile.

_Example:_

```js
window.sr = ScrollReveal();

var mobileConfig = { opacity : 0.5, duration : 200 };
var mobileConfig = { opacity : 0.2, duration : 300 };

if ( sr.tools.isMobile() ) {
  sr.reveal( '.fooClass', mobileConfig );
} else {
  sr.reveal( '.fooClass', desktopConfig );
}
```

**Comment by addedlovely** [comment]
Thanks @jlmakes, great work!
