### ISSUE TITLE
Problem with FullPageJS

### ISSUE THREAD

**Issue by fralec** [julianlloyd/scrollReveal.js#149]
The text which is to modify in the section 1 works but the text which is in the section 2, 3, etc. does not work. It has an opacity of 0. Would you know how to help me?
```JavaScript
$('#fullpage').fullpage({
    sectionsColor: [ '#f2f2f2', '#4BBFC3', '#7BAABE', 'whitesmoke', '#000' ],
    resize: true,
    autoScrolling: false,
    scrollBar: true,
    afterRender: function(){
      window.sr = new scrollReveal()
    }
});
```

**Comment by julianlloyd** [comment]
Some issues have come up before with fullPage.js, see #45 #84 #14 

This except from #45 in particular might be of some help:

> From the [fullPage.js FAQ](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions#parallax-doesnt-work-with-fullpagejs):

>  fullPage.js doesn't actually scroll the site but it changes the top or translate3d property of the site. Only when using the fullPage.js option scrollBar:true or autoScrolling:false it will actually scroll the site in a way it is accessible for the scrollTop property.
